openapi: 3.0.0
info:
  title: FooBar
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /stuff:
    get:
      summary: get stuff
      tags: []
      responses: {}
      operationId: get-stuff
    post:
      summary: create stuff
      tags: []
      responses: {}
      operationId: post-stuff
components:
  schemas: {}
